language: csharp
solution: WoodenBench-Platform.sln
mono: none
dotnet: 2.1.402
script:
 - dotnet build ./StandardLibrary/StandardLibrary.csproj
 - dotnet build ./WebManagement/WebManagement.csproj
 - dotnet build ./ServiceStatus/ServiceStatus.csproj