language: csharp
solution: WoodenBench-Platform.sln
mono: latest
dotnet: 2.1.402
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore WoodenBench-Platform.sln
script:
 - dotnet build