language: csharp
solution: WoodenBench-Platform.sln
mono: none
dotnet: 2.1.402
install:
  - apt install nuget
  - nuget restore WoodenBench-Platform.sln
script:
 - dotnet build ./StandardLibrary/StandardLibrary.csproj
 - dotnet build ./WebManagement/WebManagement.csproj
 - dotnet build ./ServiceStatus/ServiceStatus.csproj